template-suffix: ejs
dependencies:
  - dotnet
  - 

available-feature-flags:
  - name: stub-with-code-samples
    description: |
      Stub the `Program.cs` implementations with code from the codeSamples property.
      By default the implementations will throw a not-implemented error. This will error out
      if every export doesn't have at least one C# codeSample.
